export const GET_EXERCISES_REQUEST = 'GET_EXERCISES_REQUEST';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const GET_EXERCISES_FAIL = 'GET_EXERCISES_FAIL';

export const SEARCH_EXERCISES_REQUEST = 'SEARCH_EXERCISES_REQUEST';
export const SEARCH_EXERCISES_SUCCESS = 'SEARCH_EXERCISES_SUCCESS';
export const SEARCH_EXERCISES_FAIL = 'SEARCH_EXERCISES_FAIL';

export const SET_BODYPART_REQUEST = 'SET_BODYPART_REQUEST';
export const SET_BODYPART_SUCCESS = 'SET_BODYPART_SUCCESS';
export const SET_BODYPART_FAIL = 'SET_BODYPART_FAIL';